### ISSUE TITLE
An argument "currentContentObject" does not exist for this request. Code 1176558158

### ISSUE THREAD

**Issue by lukasniestroj** [topwire/topwire#15]
Hi, just tested your extension in a fresh TYPO3 12.4.4 PHP 8.1 (ddev environment). But unfortunately I instantly got this Problem:

An argument "currentContentObject" does not exist for this request. Code 1176558158. After Debugging my guess is that the TYPO3 core does handle the Fallback incorrectly on link building:

```php
    /**
     * @deprecated Remove in v13 when contentObject is no longer nullable
     */
    protected function getContentObject(): ContentObjectRenderer
    {
        if ($this->contentObject !== null) {
            return $this->contentObject;
        }

        trigger_error(
            __CLASS__ . ' relies on the current content object which should be initialized by calling ->setRequest(). The automatic fallback will be removed with TYPO3 v13.',
            E_USER_DEPRECATED
        );

        return ($contentObject = $this->getRequest()?->getArgument('currentContentObject')) instanceof ContentObjectRenderer
            ? $contentObject
            : GeneralUtility::makeInstance(ContentObjectRenderer::class);
    }
```

`$this->getRequest()?->getArgument('currentContentObject'))` will throw an NoSuchArgumentException and not returning null. I guess this was unintended but breaks your UriBuilder in the FrameViewHelper.

**Comment by helhum** [comment]
Ah, forgot to mention that in my talk. That is a TYPO3 bug, that is fixed but not released yet: https://review.typo3.org/79521

Can you please test against the current dev version of typo3 12? Should work.

**Comment by lukasniestroj** [comment]
Works! Really nice to have this available for TYPO3 <3
