### ISSUE TITLE
TYPO3 12

### ISSUE THREAD

**Issue by msollmann** [topwire/topwire#28]
Cool extension! Are there any plans for a V12 version in the near future?

**Comment by helhum** [comment]
> Cool extension! Are there any plans for a V12 version in the near future?

What exactly do you mean? It is compatible with TYPO3 v11 and TYPO3 v12.

**Comment by msollmann** [comment]
I'm sorry, didn't read it carefully enough :-(

**Comment by helhum** [comment]
> I'm sorry, didn't read it carefully enough :-(

No worries. Good we sorted it out!
