### ISSUE TITLE
Request is not Frontend

### ISSUE THREAD

**Issue by ogrosko** [topwire/topwire#30]
Hello,

we've noticed an issue with Topwire request and `f:format.date()` VH. On this [line](https://github.com/TYPO3/typo3/blob/v12.4.19/typo3/sysext/fluid/Classes/ViewHelpers/Format/DateViewHelper.php#L221) Topwire request is not resolved as **Frontend** so date is not correctly formatted in desired language

Tested on Typo3 12.4.19

**Comment by helhum** [comment]
Thanks for the report. Please provide more information and a way to reproduce your observation

**Comment by ogrosko** [comment]
Hello @helhum 
we've tested it on a minimal Typo3 instance (without project-specific features) and it works fine. It means it's our issue in a project. 

Sorry for bothering you! 🙇‍♂️
